#application config
app:
  name: tiklab-xpack
  path: ${APP_HOME}
spring:
  profiles:
    active: dev

#web config
server:
  port: 8083

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_xpack?currentSchema=public&stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: ${user.home}/tiklab/${app.name}

#enable mysql
mysql:
  embbed:
    enable: false
  server:
    port: 3306


#eas config
eas:
  embbed:
    enable: true
  address:


#dfs config
#dfs.server.enabled=false
dfs:
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}

#dcs server config

dcs:
  client:
    url: 172.10.1.11:5000
    bucket: ${app.name}

#dss config
#dss.server.enabled=false

dss:
  client:
    url: 172.10.1.11:6000
    bucket: ${app.name}

#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
ocs:
  address: http://192.168.10.14:8080


homes:
  address: http://192.168.10.14:8080
  return:
    path: ''

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

#file
file:
  path: http://file.dev.tiklab.net
repository:
  library: /Users/limingliang/publicData
  code: xpack
  address: "http://192.168.10.14:8083"




