#application config
app:
  name: tiklab-oms
  path: ${APP_HOME}
spring:
  profiles:
    active: prd

#web config
server:
  port: 8082

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.27.46.219:3306/tiklab_oms?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

DATA_HOME: ${user.home}/tiklab/${app.name}

#dfs config
#dfs.server.enabled=false
dfs:
  client:
    url: 101.132.162.74:4000
    bucket: ${app.name}

#dcs server config

dcs:
  client:
    url: 101.132.162.74:5000
    bucket: ${app.name}

#dss config
#dss.server.enabled=false

dss:
  client:
    url: 101.132.162.74:6000
    bucket: ${app.name}

#enable mysql
mysql:
  embbed:
    enable: false
  server:
    port: 3306
  version: mysql-8.0.28
  name: tiklab_oms

#eas config
eas:
  address: http://101.132.102.247:8081
  web:
    address: http://101.132.102.247:8081
  embbed:
    enable: false




#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
ocs:
  address: http://139.196.76.221:8080


homes:
  address: http://139.196.76.221:8080
  return:
    path: ''

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

db:
  path: 101.132.162.74:3306
  shell:
    path: ${APP_HOME}/script/create_db_local_02.sh


template:
  shell:
    path: ${APP_HOME}/script/create_db_local_03.sh

portal:
  return:
    path: ""

