#application config
app:
  name: tiklab-oms
  path: ${APP_HOME}
spring:
  profiles:
    active: dev

#web config
server:
  port: 8082

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.10.1.10:3306/tiklab_oms?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

DATA_HOME: ${user.home}/tiklab/${app.name}

#enable mysql
mysql:
  embbed:
    enable: false
  server:
    port: 3306
  version: mysql-8.0.28
  name: tiklab_oms

#eas config
eas:
  address: http://172.11.1.12:8080
  web:
    address: http://172.11.1.12:8080
  embbed:
    enable: false



#dfs config
#dfs.server.enabled=false
dfs:
  client:
    url: 172.10.1.11:4000
    bucket: ${app.name}

#dcs server config

dcs:
  client:
    url: 172.10.1.11:5000
    bucket: ${app.name}

#dss config
#dss.server.enabled=false

dss:
  client:
    url: 172.10.1.11:6000
    bucket: ${app.name}

#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
ocs:
  service:
    address: http://192.168.10.19:8080


homes:
  address: http://192.168.10.19:8080
  return:
    path: ''

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

db:
  path: 127.0.0.1:3306
  shell:
    path: ${APP_HOME}/script/create_db_local_02.sh


template:
  shell:
    path: ${APP_HOME}/script/create_db_local_02.sh

portal:
  return:
    path: ""

